name: cv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - opencv-contrib-python
    - scipy
    - scikit-learn
    - matplotlib

# conda remove --name cv --all
# conda env create -f environment.yml 
